title: Buddhika Jayawardana # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a dedicated mathematician and educator with a strong research, teaching, and applied mathematics background. Currently serving as a <b>Postdoctoral Research Fellow</b> at the FDA National Center for Toxicological Research, I focus on using <b>machine learning</b> techniques to address pressing issues in racial disparities and women's health.
  <br><br>
  I completed my <b>PhD in Mathematics</b> at the University of Texas at Dallas, focusing on developing efficient numerical methods that preserve the geometric properties of Hamiltonian systems. My teaching experience spans a variety of undergraduate courses, including calculus and linear algebra, and I am genuinely passionate about making mathematics accessible and exciting for students from diverse backgrounds.
  <br><br>
  I am actively seeking opportunities in an academic institute where I can inspire the next generation of mathematicians and contribute meaningfully to the academic community. I look forward to engaging with colleagues and students with a passion for mathematics and collaborative learning!
  <br><br>
  
theme: jekyll-theme-minimal

# With expertise in Python, R, MATLAB, and advanced computational methods, I connect theoretical insights with practical applications effectively. My proficiency in machine learning, numerical analysis, and cloud technologies enables me to bring academic concepts to life in meaningful ways.
# <br><br>
